version: '3'
services:
  app:
    build:
      args:
        NODE_ENV: development
    volumes:
      - ./src:/app/src
    command: yarn start:dev

  mongo-express:
    image: mongo-express
    ports:
      - '8081:8081'
    environment:
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_MONGODB_ADMINUSERNAME: '${MONGODB_USER}'
      ME_CONFIG_MONGODB_ADMINPASSWORD: '${MONGODB_PWD}'
    depends_on:
      - mongodb
